#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
	CREATE USER metabase WITH PASSWORD 'metabase';
	CREATE DATABASE metabase;
	GRANT ALL PRIVILEGES ON DATABASE metabase TO metabase;

	\c metabase;

	GRANT ALL PRIVILEGES ON SCHEMA public TO metabase;
	GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO metabase;
	ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO metabase;
	ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO metabase;
EOSQL
