#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
	CREATE USER n8n WITH PASSWORD 'n8n';
	CREATE DATABASE n8n;
	GRANT ALL PRIVILEGES ON DATABASE n8n TO n8n;

	\c n8n;

	GRANT ALL PRIVILEGES ON SCHEMA public TO n8n;
	GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO n8n;
	ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO n8n;
	ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO n8n;
EOSQL
