#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
	CREATE USER litellm WITH PASSWORD 'litellm';
	CREATE DATABASE litellm;
	GRANT ALL PRIVILEGES ON DATABASE litellm TO litellm;

	\c litellm;

	GRANT ALL PRIVILEGES ON SCHEMA public TO litellm;
	GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO litellm;
	ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO litellm;
	ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO litellm;
EOSQL
