name: Notify Discord on Push

on:
  push:
    branches:
      - master

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          CHANGES=$(jq -r '.commits[] | "- \(.message)"' < $GITHUB_EVENT_PATH)
          CHANGES=$(echo "$CHANGES" | sed ':a;N;$!ba;s/\n/\\n/g')
          REPO_URL=https://github.com/${{ github.repository }}
          curl -H "Content-Type: application/json" -X POST -d "{\"username\": \"GitHub Bot\", \"content\": \"@${GITHUB_ACTOR}, [${GITHUB_REPOSITORY}](${REPO_URL}) projesi için güncellemeler yayınlamıştır.\n\n**Yapılan değişiklikler:**\n${CHANGES}\n\n✅ Lütfen yerel geliştirme ortamınızı güncellemek için ana dizinde \`./update.sh\` komutunu çalıştırın.\"}" $DISCORD_WEBHOOK_URL
